spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://notification-db:5432/notificationDB
    username: xtremeneon
    password: Divyansh@04
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.divyansh.linkedin.*

server:
  port: 9040
  servlet:
    context-path: /notifications

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
