spring:
  application:
    name: posts-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



  datasource:
    url: jdbc:postgresql://${DB_SERVICE:posts-db}:5432/%{DB_NAME:postsDB}
    username: ${DB_USER:xtremeneon}
    password: ${DB_PASSWORD:Divyansh@04}

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.apache.kafka: DEBUG
server:
  port: 8081
  servlet:
    context-path: /posts

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true